version: '2'
services:
  lora-concentrator:
    build: ./basicstation
    expose:
      - "8887"
    network_mode: host
    privileged: true
  notecard-server:
    build: ./notecard-server
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - "8765:8765"
    privileged: true